source 'https://rubygems.org'


gem 'rails', github: 'rails/rails'
# gem 'rails', '~> 5.0.0'
# Use sqlite3 as the database for Active Record or postgresql
gem 'sqlite3'
# gem 'pg', '~> 0.18.4'
#use jsonapi- resources or active model for the json response formating
gem 'jsonapi-resources', git: 'https://github.com/cerebris/jsonapi-resources.git',
                         branch: 'rails5'
# gem 'active_model_serializers', '~> 0.9.3'

# Use Puma as the app server
gem 'puma', '~> 3.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
