# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a832a89870bfe4e6728e1d432befdb61d3749f75b2defaf736928e8dd49348af0f0d4327771d85453fef8217e18506df4b14cbf3bc96e9f8eaa037421a0884b

test:
  secret_key_base: 49fb9f84ca2137df7fc28d63a01f63af77f9057e9718f5444c212ef4cdfde09f8f1c2d843af9986cbef3d1f5c1657488cefd53864ceb55cfdbc1e26faaf8f960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
